baseURL = 'https://apostle.rezzamula.com/'
languageCode = 'en-us'
title = 'Apostle'
enableRobotsTXT = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  author = 'authors'
  story = 'stories'

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "tags"
        weight = 99
