[[redirects]]
  from = "/img/*"
  to = "https://i.imgur.com/:splat"
  status = 200
  force = true
  headers = {Cache-Control = "public, max-age=31536000, s-maxage=31536000, immutable"}

[[headers]]
  for = "/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, s-maxage=31536000"